### ISSUE TITLE
Support for project files written by Poetry

### ISSUE THREAD

**Issue by ghisvail** [sphinx-toolbox/sphinx-pyproject#29]
Using `sphinx-pyproject` on a project setup with Poetry results in the following error:

`dom_toml.parser.BadConfigError: No 'project' table found in .../pyproject.toml`

Indeed the project metadata are stored in the `[tool.poetry]` table, instead of `project`.

I wonder whether it would be possible to support Poetry's setup by providing a `project_table` optional parameter defaulting to `project` which Poetry users could override to `tool.poetry`?

**Comment by domdfcoding** [comment]
I'll happily accept a PR adding support for poetry support, if poetry supporting PEP 621 is a way off. 

What's required is a different version of the `ProjectParser` class that parses from `[tool.poetry]` instead of `[project]`, and a bit of logic in ``SphinxConfig.__init__`` to decide on which table and class to use.
